import { error, fail, redirect } from '@sveltejs/kit';
import type { PageServerLoad, Actions } from './$types';
import { parseRepoUrl, getRepoInfo, getReadmeContent, createBranch, createOrUpdateFile, createPullRequest } from '$lib/server/github';
import { generateReadme } from '$lib/server/claude';
import { SUBMIT_PROJECT_XP } from '$lib/constants';

export const load: PageServerLoad = async ({ params, locals: { supabase, session } }) => {
	if (!session) throw redirect(303, '/auth/login');

	const { data: project } = await supabase
		.from('projects')
		.select('*')
		.eq('id', params.id)
		.single();

	if (!project) throw error(404, 'Project not found');
	if (project.submitted_by !== session.user.id) throw error(403, 'Only the project owner can generate a README');

	const { data: ghConn } = await supabase
		.from('github_connections')
		.select('github_username')
		.eq('user_id', session.user.id)
		.single();

	return {
		project,
		githubConnected: !!ghConn
	};
};

export const actions: Actions = {
	generate: async ({ params, locals: { supabase, session } }) => {
		if (!session) return fail(401, { error: 'Not authenticated' });

		const { data: project } = await supabase
			.from('projects')
			.select('*')
			.eq('id', params.id)
			.single();

		if (!project) return fail(404, { error: 'Project not found' });
		if (!project.repo_url) return fail(400, { error: 'No repository URL' });

		const { data: ghConn } = await supabase
			.from('github_connections')
			.select('access_token')
			.eq('user_id', session.user.id)
			.single();

		if (!ghConn) return fail(400, { error: 'GitHub not connected' });

		const parsed = parseRepoUrl(project.repo_url);
		if (!parsed) return fail(400, { error: 'Invalid GitHub URL' });

		try {
			const [repoInfo, currentReadme] = await Promise.all([
				getRepoInfo(ghConn.access_token, parsed.owner, parsed.repo),
				getReadmeContent(ghConn.access_token, parsed.owner, parsed.repo)
			]);

			const readme = await generateReadme({
				projectTitle: project.title,
				projectDescription: project.description,
				problemStatement: project.problem_statement,
				solutionSummary: project.solution_summary,
				techStack: project.tech_stack || [],
				aiToolsUsed: project.ai_tools_used || [],
				currentReadme,
				repoLanguages: Object.keys(repoInfo.languages)
			});

			return { success: true, readme, hasExisting: !!currentReadme };
		} catch (err: any) {
			return fail(500, { error: `Generation failed: ${err.message}` });
		}
	},

	pushPr: async ({ params, request, locals: { supabase, session } }) => {
		if (!session) return fail(401, { error: 'Not authenticated' });

		const formData = await request.formData();
		const readmeContent = formData.get('readme') as string;

		if (!readmeContent?.trim()) return fail(400, { error: 'README content is empty' });

		const { data: project } = await supabase
			.from('projects')
			.select('*')
			.eq('id', params.id)
			.single();

		if (!project?.repo_url) return fail(400, { error: 'No repository URL' });

		const { data: ghConn } = await supabase
			.from('github_connections')
			.select('access_token')
			.eq('user_id', session.user.id)
			.single();

		if (!ghConn) return fail(400, { error: 'GitHub not connected' });

		const parsed = parseRepoUrl(project.repo_url);
		if (!parsed) return fail(400, { error: 'Invalid GitHub URL' });

		try {
			const repoInfo = await getRepoInfo(ghConn.access_token, parsed.owner, parsed.repo);
			const branchName = `trackam/readme-${Date.now()}`;

			await createBranch(
				ghConn.access_token,
				parsed.owner,
				parsed.repo,
				branchName,
				repoInfo.default_branch
			);

			await createOrUpdateFile(
				ghConn.access_token,
				parsed.owner,
				parsed.repo,
				'README.md',
				readmeContent,
				'docs: Update README (generated by Sinai TrackAM)',
				branchName
			);

			const pr = await createPullRequest(
				ghConn.access_token,
				parsed.owner,
				parsed.repo,
				{
					title: 'docs: Update README (generated by Sinai TrackAM)',
					body: `This README was generated by [Sinai TrackAM](${project.demo_url || '#'}) based on the project submission details.\n\n---\n*Auto-generated by Sinai TrackAM AI*`,
					head: branchName,
					base: repoInfo.default_branch
				}
			);

			// Award XP for docs contribution
			await supabase.rpc('add_xp', { user_id: session.user.id, amount: Math.floor(SUBMIT_PROJECT_XP / 2) });

			return { success: true, prUrl: pr.html_url, prNumber: pr.number };
		} catch (err: any) {
			return fail(500, { error: `Failed to create PR: ${err.message}` });
		}
	}
};
